version: "3.8"

services:
  gmail_scheduler:
    build: .
    command: python scheduler.py
    env_file: /etc/bot/.env         # Suggested path to place the .env file, so only "sudo" users can access it.
    volumes:
      - ./log.txt:/app/log.txt
      - ./status.json:/app/status.json

  gmail_dashboard:
    build: .
    command: python app.py
    env_file: /etc/bot/.env       # Suggested path to place the .env file, so only "sudo" users can access it.
    ports:
      - "5002:5000"
    volumes:
      - ./log.txt:/app/log.txt
      - ./status.json:/app/status.json
